name: kanpractice
description: A Flutter project to learn and study the different kanjis.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable:
  cupertino_icons: ^1.0.2
  sqflite:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  easy_localization:
  provider:
  shared_preferences:
  path:
  json_annotation: ^4.3.0
  syncfusion_flutter_gauges:
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  percent_indicator:
  kana_kit:
  timeago:
  flutter_launcher_icons:
  package_info:
  url_launcher:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - documentation/
    - lib/core/localization/
